Add asset manifest sanity check to pr-preview

diff --git a/.github/workflows/pr-preview.yml b/.github/workflows/pr-preview.yml
--- a/.github/workflows/pr-preview.yml
+++ b/.github/workflows/pr-preview.yml
@@ -131,8 +131,13 @@ jobs:
         timeout-minutes: 120
         run: |
           sudo apt update
-          sudo apt install rsync
+          sudo apt install rsync jq
           make package
+          INDEX_NAME=$(jq '."index.html".name' lib/streamlit/static/manifest.json)
+          if [ "${INDEX_NAME}" != "index-testFailure" ]:
+            echo 'manifest.json file is missing or malformatted'
+            exit 1
+          fi
       - name: Store Whl File
         uses: actions/upload-artifact@v4
         with:
